version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && pnpm install && pnpm dev"
